// Array de productos - Catálogo de Juguetería
// Total de productos: 30

const products = [
    { name: "Producto 1", category: "jugueteria", image: "imagenes/jugueteria/1.jpeg" },
    { name: "Producto 2", category: "jugueteria", image: "imagenes/jugueteria/2.jpeg" },
    { name: "Producto 3", category: "jugueteria", image: "imagenes/jugueteria/3.jpeg" },
    { name: "Producto 4", category: "jugueteria", image: "imagenes/jugueteria/4.jpeg" },
    { name: "Producto 5", category: "jugueteria", image: "imagenes/jugueteria/5.jpeg" },
    { name: "Producto 6", category: "jugueteria", image: "imagenes/jugueteria/6.jpeg" },
    { name: "Producto 7", category: "jugueteria", image: "imagenes/jugueteria/7.jpeg" },
    { name: "Producto 8", category: "jugueteria", image: "imagenes/jugueteria/8.jpeg" },
    { name: "Producto 9", category: "jugueteria", image: "imagenes/jugueteria/9.jpeg" },
    { name: "Producto 10", category: "jugueteria", image: "imagenes/jugueteria/10.jpeg" },
    { name: "Producto 11", category: "jugueteria", image: "imagenes/jugueteria/11.jpeg" },
    { name: "Producto 12", category: "jugueteria", image: "imagenes/jugueteria/12.jpeg" },
    { name: "Producto 13", category: "jugueteria", image: "imagenes/jugueteria/13.jpeg" },
    { name: "Producto 14", category: "jugueteria", image: "imagenes/jugueteria/14.jpeg" },
    { name: "Producto 15", category: "jugueteria", image: "imagenes/jugueteria/15.jpeg" },
    { name: "Producto 16", category: "jugueteria", image: "imagenes/jugueteria/16.jpeg" },
    { name: "Producto 17", category: "jugueteria", image: "imagenes/jugueteria/17.jpeg" },
    { name: "Producto 18", category: "jugueteria", image: "imagenes/jugueteria/18.jpeg" },
    { name: "Producto 19", category: "jugueteria", image: "imagenes/jugueteria/19.jpeg" },
    { name: "Producto 20", category: "jugueteria", image: "imagenes/jugueteria/20.jpeg" },
    { name: "Producto 21", category: "jugueteria", image: "imagenes/jugueteria/21.jpeg" },
    { name: "Producto 22", category: "jugueteria", image: "imagenes/jugueteria/22.jpeg" },
    { name: "Producto 23", category: "jugueteria", image: "imagenes/jugueteria/23.jpeg" },
    { name: "Producto 24", category: "jugueteria", image: "imagenes/jugueteria/24.jpeg" },
    { name: "Producto 25", category: "jugueteria", image: "imagenes/jugueteria/25.jpeg" },
    { name: "Producto 26", category: "jugueteria", image: "imagenes/jugueteria/26.jpeg" },
    { name: "Producto 27", category: "jugueteria", image: "imagenes/jugueteria/27.jpeg" },
    { name: "Producto 28", category: "jugueteria", image: "imagenes/jugueteria/28.jpeg" },
    { name: "Producto 29", category: "tecnologia", image: "imagenes/tecnologia/29.jpeg" },
    { name: "Producto 30", category: "limpieza", image: "imagenes/limpieza/30.jpeg" },
    { name: "Producto 31", category: "jugueteria", image: "imagenes/jugueteria/31.jpeg" },
    { name: "Producto 32", category: "jugueteria", image: "imagenes/jugueteria/32.jpeg" },
    { name: "Producto 33", category: "jugueteria", image: "imagenes/jugueteria/33.jpeg" },
    { name: "Producto 34", category: "jugueteria", image: "imagenes/jugueteria/34.jpeg" },
    { name: "Producto 35", category: "jugueteria", image: "imagenes/jugueteria/35.jpeg" },
    { name: "Producto 36", category: "jugueteria", image: "imagenes/jugueteria/36.jpeg" },
    { name: "Producto 37", category: "jugueteria", image: "imagenes/jugueteria/37.jpeg" },
    { name: "Producto 38", category: "jugueteria", image: "imagenes/jugueteria/38.jpeg" },
    { name: "Producto 39", category: "jugueteria", image: "imagenes/jugueteria/39.jpeg" },
    { name: "Producto 40", category: "jugueteria", image: "imagenes/jugueteria/40.jpeg" },
    { name: "Producto 41", category: "jugueteria", image: "imagenes/jugueteria/41.jpeg" },
    { name: "Producto 42", category: "jugueteria", image: "imagenes/jugueteria/42.jpeg" },
    { name: "Producto 43", category: "jugueteria", image: "imagenes/jugueteria/43.jpeg" },
    { name: "Producto 44", category: "jugueteria", image: "imagenes/jugueteria/44.jpeg" },
    { name: "Producto 45", category: ["tecnologia", "escolar"], image: "imagenes/tecnologia/45.jpeg" },
    { name: "Producto 46", category: "cuidado-personal", image: "imagenes/cuidadoPersonal/46.jpeg" },
    { name: "Producto 47", category: "escolar", image: "imagenes/escolar/47.jpeg" },
    { name: "Producto 48", category: "escolar", image: "imagenes/escolar/48.jpeg" },
    { name: "Producto 49", category: ["escolar", "arte"], image: "imagenes/escolar/49.jpeg" },
    { name: "Producto 50", category: "escolar", image: "imagenes/escolar/50.jpeg" },
    { name: "Producto 51", category: "escolar", image: "imagenes/escolar/51.jpeg" },
    { name: "Producto 60", category: ["hogar", "limpieza"], image: "imagenes/limpieza/52.jpeg" }, 
    { name: "Producto 53", category: "escolar", image: "imagenes/escolar/53.jpeg" },
    { name: "Producto 54", category: "escolar", image: "imagenes/escolar/54.jpeg" },
    { name: "Producto 55", category: "escolar", image: "imagenes/escolar/55.jpeg" },
    { name: "Producto 56", category: "limpieza", image: "imagenes/limpieza/56.jpeg" },
    { name: "Producto 57", category: "limpieza", image: "imagenes/limpieza/57.jpeg" },
    { name: "Producto 58", category: "hogar", image: "imagenes/hogar/58.jpeg" },
    { name: "Producto 59", category: "arte", image: "imagenes/arte/59.jpeg" },
    { name: "Producto 60", category: ["cuidado-personal", "limpieza"], image: "imagenes/cuidadoPersonal/60.jpeg" }, 
    { name: "Producto 61", category: "escolar", image: "imagenes/escolar/61.jpeg" },
    { name: "Producto 62", category: "escolar", image: "imagenes/escolar/62.jpeg" },
    { name: "Producto 63", category: ["arte","hogar"], image: "imagenes/arte/63.jpeg" },
    { name: "Producto 64", category: "escolar", image: "imagenes/escolar/64.jpeg" },
    { name: "Producto 65", category: "escolar", image: "imagenes/escolar/65.jpeg" },
    { name: "Producto 66", category: "escolar", image: "imagenes/escolar/66.jpeg" },
    { name: "Producto 67", category: "papeleria", image: "imagenes/papeleria/67.jpeg" },
    { name: "Producto 68", category: ["escolar", "arte"], image: "imagenes/arte/68.jpeg" }, 
    { name: "Producto 69", category: ["escolar", "arte"], image: "imagenes/escolar/69.jpeg" }, 
    { name: "Producto 70", category: ["escolar","hogar"], image: "imagenes/escolar/70.jpeg" }, 
    { name: "Producto 71", category: ["escolar", "oficina","hogar"], image: "imagenes/escolar/71.jpeg" }, 
    { name: "Producto 72", category: ["escolar", "arte"], image: "imagenes/arte/72.jpeg" }, 
    { name: "Producto 73", category: ["hogar", "limpieza"], image: "imagenes/hogar/73.jpeg" },
    { name: "Producto 74", category: ["escolar", "arte"], image: "imagenes/arte/74.jpeg" },
    { name: "Producto 75", category: ["escolar", "arte"], image: "imagenes/arte/75.jpeg" }, 
    { name: "Producto 76", category: ["escolar", "arte","hogar"], image: "imagenes/arte/76.jpeg" },
    { name: "Producto 77", category: "hogar", image: "imagenes/hogar/77.jpeg" }, 
    { name: "Producto 78", category: ["oficina", "hogar"], image: "imagenes/oficina/78.jpeg" },
    { name: "Producto 79", category: ["oficina", "escolar"], image: "imagenes/oficina/79.jpeg" },
    { name: "Producto 80", category: "jugueteria", image: "imagenes/jugueteria/80.jpeg" },
    { name: "Producto 81", category: ["escolar", "arte"], image: "imagenes/escolar/81.jpeg" },
    { name: "Producto 82", category: "jugueteria", image: "imagenes/jugueteria/82.jpeg" },
    { name: "Producto 83", category: ["oficina", "escolar"], image: "imagenes/oficina/83.jpeg" },
    { name: "Producto 84", category: "jugueteria", image: "imagenes/jugueteria/84.jpeg" },
    { name: "Producto 85", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/85.jpeg" },
    { name: "Producto 86", category: ["hogar", "cuidado-personal"], image: "imagenes/cuidadoPersonal/86.jpeg" },
    { name: "Producto 87", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/87.jpeg" },
    { name: "Producto 88", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/88.jpeg" },
    { name: "Producto 89", category: ["jugueteria", "escolar"], image: "imagenes/jugueteria/89.jpeg" },
    { name: "Producto 90", category: ["cuidado-personal","limpieza"], image: "imagenes/cuidadoPersonal/90.jpeg" },
    { name: "Producto 91", category: ["tecnologia", "hogar"], image: "imagenes/tecnologia/91.jpeg" },
    { name: "Producto 92", category: "tecnologia", image: "imagenes/tecnologia/92.jpeg" },
    { name: "Producto 93", category: "hogar", image: "imagenes/hogar/93.jpeg" },
    { name: "Producto 94", category: ["tecnologia","hogar"], image: "imagenes/tecnologia/94.jpeg" },
    { name: "Producto 95", category: ["cuidado-personal","hogar"], image: "imagenes/cuidadoPersonal/95.jpeg" },
    { name: "Producto 96", category: "hogar", image: "imagenes/hogar/96.jpeg" },
    { name: "Producto 97", category: ["arte","escolar"], image: "imagenes/arte/97.jpeg" },
    { name: "Producto 98", category: ["hogar","cuidado-personal"], image: "imagenes/hogar/98.jpeg" },
    { name: "Producto 99", category: "hogar", image: "imagenes/hogar/99.jpeg" },
    { name: "Producto 100", category: ["cuidado-personal","hogar"], image: "imagenes/cuidadoPersonal/100.jpeg" },
    { name: "Producto 101", category: ["arte","hogar"], image: "imagenes/arte/101.jpeg" },
    { name: "Producto 102", category: ["escolar","arte"], image: "imagenes/escolar/102.jpeg" },
    { name: "Producto 103", category: ["hogar","tecnologia"], image: "imagenes/hogar/103.jpeg" },
    { name: "Producto 104", category: ["escolar","arte"], image: "imagenes/escolar/104.jpeg" },
    { name: "Producto 105", category: ["escolar","arte"], image: "imagenes/escolar/105.jpeg" },
    { name: "Producto 106", category: ["escolar","arte"], image: "imagenes/escolar/106.jpeg" },
    { name: "Producto 107", category: ["escolar","arte"], image: "imagenes/escolar/107.jpeg" },
    { name: "Producto 108", category: ["escolar","arte"], image: "imagenes/escolar/108.jpeg" },
    { name: "Producto 109", category: ["hogar","cuidado-personal"], image: "imagenes/hogar/109.png" },
    { name: "Producto 110", category: ["escolar","oficina"], image: "imagenes/escolar/110.jpeg" },
    { name: "Producto 111", category: "dulces", image: "imagenes/dulces/111.jpeg" },
    { name: "Producto 112", category: "dulces", image: "imagenes/dulces/112.jpeg" },
    { name: "Producto 113", category: "dulces", image: "imagenes/dulces/113.jpeg" },
    { name: "Producto 114", category: "dulces", image: "imagenes/dulces/114.jpeg" },
    { name: "Producto 115", category: "dulces", image: "imagenes/dulces/115.jpeg" },
    { name: "Producto 116", category: "dulces", image: "imagenes/dulces/116.jpeg" },
    { name: "Producto 117", category: "dulces", image: "imagenes/dulces/117.jpeg" },
    { name: "Producto 118", category: "dulces", image: "imagenes/dulces/118.jpeg" },
    { name: "Producto 119", category: "dulces", image: "imagenes/dulces/119.jpeg" },
    { name: "Producto 120", category: "dulces", image: "imagenes/dulces/120.jpeg" },
    { name: "Producto 121", category: "dulces", image: "imagenes/dulces/121.jpeg" },
    { name: "Producto 122", category: "dulces", image: "imagenes/dulces/122.jpeg" },
    { name: "Producto 123", category: ["escolar","arte"], image: "imagenes/escolar/123.jpeg" },
    { name: "Producto 124", category: "halloween", image: "imagenes/halloween/124.jpeg" },
    { name: "Producto 125", category: "halloween", image: "imagenes/halloween/125.jpeg" },
    { name: "Producto 126", category: "halloween", image: "imagenes/halloween/126.jpeg" },
    { name: "Producto 127", category: "halloween", image: "imagenes/halloween/127.jpeg" },
    { name: "Producto 128", category: "halloween", image: "imagenes/halloween/128.jpeg" },
    { name: "Producto 129", category: "dulces", image: "imagenes/dulces/129.jpeg" },
    { name: "Producto 130", category: "hogar", image: "imagenes/hogar/130.jpeg" },
    { name: "Producto 131", category: "halloween", image: "imagenes/halloween/131.jpeg" },
    { name: "Producto 132", category: ["escolar","arte"], image: "imagenes/escolar/132.jpeg" },
    { name: "Producto 133", category: ["escolar","arte"], image: "imagenes/escolar/133.jpeg" },
    { name: "Producto 134", category: ["escolar","arte"], image: "imagenes/escolar/134.jpeg" },
    { name: "Producto 135", category: "hogar", image: "imagenes/hogar/135.jpeg" },
    { name: "Producto 136", category: "hogar", image: "imagenes/hogar/136.jpeg" },
    { name: "Producto 137", category: ["arte","escolar"], image: "imagenes/arte/137.jpeg" },
    { name: "Producto 138", category: ["cuidado-personal", "hogar"], image: "imagenes/cuidadoPersonal/138.jpeg" }, 
    { name: "Producto 139", category: ["escolar", "hogar"], image: "imagenes/escolar/139.jpeg" },
    { name: "Producto 140", category: "papeleria", image: "imagenes/papeleria/140.jpeg" },  
    { name: "Producto 141", category: "dulces", image: "imagenes/dulces/141.jpeg" },
    { name: "Producto 142", category: "tecnologia", image: "imagenes/tecnologia/142.jpeg" },
    { name: "Producto 143", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/143.jpeg" },
    { name: "Producto 144", category: ["jugueteria", "arte"], image: "imagenes/jugueteria/144.jpeg" },
    { name: "Producto 145", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/145.jpeg" },
    { name: "Producto 146", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/146.jpeg" },
    { name: "Producto 147", category: "fiestas-patrias", image: "imagenes/fiestasPatrias/147.jpeg" },
    { name: "Producto 148", category: "fiestas-patrias", image: "imagenes/fiestasPatrias/148.jpeg" },
    { name: "Producto 149", category: ["hogar", "oficina"], image: "imagenes/hogar/149.jpeg" },
    { name: "Producto 150", category: ["escolar", "arte", "hogar"], image: "imagenes/escolar/150.jpeg" },
    { name: "Producto 151", category: "hogar", image: "imagenes/hogar/151.jpeg" },
    { name: "Producto 152", category: ["cuidado-personal","hogar"], image: "imagenes/cuidadoPersonal/152.jpeg" },
    { name: "Producto 153", category: "dulces", image: "imagenes/dulces/153.jpeg" },
    { name: "Producto 154", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/154.jpeg" },
    { name: "Producto 155", category: ["escolar", "arte"], image: "imagenes/escolar/155.jpeg" },
    { name: "Producto 156", category: ["hogar", "cuidado-personal"], image: "imagenes/hogar/156.jpeg" },
];
