// Array de productos - Catálogo de Juguetería
// Total de productos: 30

const products = [
    { name: "Producto 1", category: "jugueteria", image: "imagenes/jugueteria/1.jpeg" },
    { name: "Producto 2", category: "jugueteria", image: "imagenes/jugueteria/2.jpeg" },
    { name: "Producto 3", category: "jugueteria", image: "imagenes/jugueteria/3.jpeg" },
    { name: "Producto 4", category: "jugueteria", image: "imagenes/jugueteria/4.jpeg" },
    { name: "Producto 5", category: "jugueteria", image: "imagenes/jugueteria/5.jpeg" },
    { name: "Producto 6", category: "jugueteria", image: "imagenes/jugueteria/6.jpeg" },
    { name: "Producto 7", category: "jugueteria", image: "imagenes/jugueteria/7.jpeg" },
    { name: "Producto 8", category: "jugueteria", image: "imagenes/jugueteria/8.jpeg" },
    { name: "Producto 9", category: "jugueteria", image: "imagenes/jugueteria/9.jpeg" },
    { name: "Producto 10", category: "jugueteria", image: "imagenes/jugueteria/10.jpeg" },
    { name: "Producto 11", category: "jugueteria", image: "imagenes/jugueteria/11.jpeg" },
    { name: "Producto 12", category: "jugueteria", image: "imagenes/jugueteria/12.jpeg" },
    { name: "Producto 13", category: "jugueteria", image: "imagenes/jugueteria/13.jpeg" },
    { name: "Producto 14", category: "jugueteria", image: "imagenes/jugueteria/14.jpeg" },
    { name: "Producto 15", category: "jugueteria", image: "imagenes/jugueteria/15.jpeg" },
    { name: "Producto 16", category: "jugueteria", image: "imagenes/jugueteria/16.jpeg" },
    { name: "Producto 17", category: "jugueteria", image: "imagenes/jugueteria/17.jpeg" },
    { name: "Producto 18", category: "jugueteria", image: "imagenes/jugueteria/18.jpeg" },
    { name: "Producto 19", category: "jugueteria", image: "imagenes/jugueteria/19.jpeg" },
    { name: "Producto 20", category: "jugueteria", image: "imagenes/jugueteria/20.jpeg" },
    { name: "Producto 21", category: "jugueteria", image: "imagenes/jugueteria/21.jpeg" },
    { name: "Producto 22", category: "jugueteria", image: "imagenes/jugueteria/22.jpeg" },
    { name: "Producto 23", category: "jugueteria", image: "imagenes/jugueteria/23.jpeg" },
    { name: "Producto 24", category: "jugueteria", image: "imagenes/jugueteria/24.jpeg" },
    { name: "Producto 25", category: "jugueteria", image: "imagenes/jugueteria/25.jpeg" },
    { name: "Producto 26", category: "jugueteria", image: "imagenes/jugueteria/26.jpeg" },
    { name: "Producto 27", category: "jugueteria", image: "imagenes/jugueteria/27.jpeg" },
    { name: "Producto 28", category: "jugueteria", image: "imagenes/jugueteria/28.jpeg" },
    { name: "Producto 29", category: "tecnologia", image: "imagenes/tecnologia/29.jpeg" },
    { name: "Producto 30", category: "limpieza", image: "imagenes/limpieza/30.jpeg" }
];
